[package]
name = "mid-util"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
derive-where = "1.0.0"
once_cell = "1.13.1"
thiserror = "1.0.32"

[dev-dependencies]
fastrand = "1.8.0"
macroquad = "0.3.23"
mid-util = { path = "../util" }
