[package]
name = "mid-util"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
derive-where = "1.0.0"
itertools = "0.10.3"
log = "0.4.17"
once_cell = "1.14.0"
thiserror = "1.0.32"

[dev-dependencies]
fastrand = "1.8.0"
macroquad = "0.3.24"
mid-util = { path = "../util" }
